### ISSUE TITLE
adding etags & original filename & format 

### ISSUE THREAD

**Issue by tofixx** [pichasso/pichasso#19]
[x] etag
[x] format
[] filename

https://github.com/jshttp/etag

**Comment by tofixx** [comment]
filename is missing by now but shouldn't we remove filename and all meta data from images instead? @franticBIT

**Comment by franticBIT** [comment]
I haven't had a look at it, but is it even present after processing? The filename should be carried over IMHO.

**Comment by tofixx** [comment]
filename and other metadata will be ignored
