### ISSUE TITLE
Add doku

### ISSUE THREAD

**Issue by jprberlin** [pichasso/pichasso#33]

**Comment by maxklenk** [comment]
The API is documented now.

The README of this project could be improved by explaining why and how to use the image service. (Problem,Solution,How to Add).

**Comment by maxklenk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dokument Image Service](https://trello.com/c/5dwbUlF3/38-dokument-image-service)

**Comment by maxklenk** [comment]
Dokument npm commands

**Comment by JanKhstll** [comment]
TODO adjust the source code sample and display as HTML.

**Comment by tofixx** [comment]
done
