### ISSUE TITLE
we should ignore missing content type

### ISSUE THREAD

**Issue by tofixx** [pichasso/pichasso#43]
i think we should check for accepted content types but ignore missing type:

http://crop.jbbr.net/image?url=https%3A%2F%2Fstatic.pexels.com%2Fphotos%2F36478%2Famazing-beautiful-beauty-blue.jpg&width=250&height=250&crop=fill&gravity=entropy&format=&quality=80

**Comment by franticBIT** [comment]
That should actually be the case, if I'm not wrong... not sure when it got broken. :/Am 15.06.2017 3:47 nachm. schrieb "Tobias W." <notifications@github.com>:i think we should check for accepted content types but ignore missing type:
http://crop.jbbr.net/image?url=https%3A%2F%2Fstatic.pexels.com%2Fphotos%2F36478%2Famazing-beautiful-beauty-blue.jpg&width=250&height=250&crop=fill&gravity=entropy&format=&quality=80
