### ISSUE TITLE
Image gets cropped with height as only parameter

### ISSUE THREAD

**Issue by franticBIT** [pichasso/pichasso#55]
Width works as its supposed to:
https://images.open.hpi.de/image?url=83e9b527-5082-4423-a4bc-30d7b22accb6&width=200

But here somehow the image gets cropped with an arbitrary width:
https://images.open.hpi.de/image?url=83e9b527-5082-4423-a4bc-30d7b22accb6&height=200

**Comment by maxklenk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix image service bugs](https://trello.com/c/FtDJU6Hj/37-fix-image-service-bugs)
