### ISSUE TITLE
Query params vs. params in path

### ISSUE THREAD

**Issue by j-slvr** [pichasso/pichasso#7]
There are two ways to design the GET route. 

## 1. Query params
```
/api/image/{id}?{width}&{height}&{crop}&{compress}&{format}

Example: /api/image/1337&width=100&height=200&crop=fill&compress=80&format=jpg
```
## 2. Params as part of the path (virtual path)
```
/api/image/{id}/{width}/{height}/{crop}/{compress}/{format}/{face}

Example: /api/image/1337/width_100/height_200/crop_fill/compress_80/format_jpg
```
## Implications

I am not 100% sure, but the design of the route could have an impact on how the browser handles the caching of those images. 
Just leaving this here that we keep it in mind.

**Comment by maxklenk** [comment]
We decided to keep the query parameters because the url encoding (when it is not an ID) will be more complex.
