### ISSUE TITLE
Data source config paradigms

### ISSUE THREAD

**Issue by j-slvr** [pichasso/pichasso#8]
## 1. Set Base URL
- Configure a base url where to look for the raw data.
- `:id` param in request is then mapped to the base url of the data source

## 2. Set DB credentials
- Configure databse credentials
- Request files directly from DB with `:id`

## 3. No source config set. (source URL part of request)
- Dont configure a data source
- Source URL is set per request as part of the URL/query params

## Caching
In either way, the optimized files should be cached internally (or later in a distributed cache)

**Comment by tofixx** [comment]
1 & 3 is done in #20

**Comment by tofixx** [comment]
we will skip 2. sample until it will be required.
