### ISSUE TITLE
JPEG headers are set for webp image

### ISSUE THREAD

**Issue by maxklenk** [pichasso/pichasso#85]
The following image is returned as webp (as requested) but has `Content-Type:image/jpeg` set.

![](https://picasso.openhpi.de/image?type=webp&file=https://staging-openhpi.azureedge.net/files/ebc91af7-c205-463c-9cd5-b54fb86644d2&width=310)

https://picasso.openhpi.de/image?type=webp&file=https://staging-openhpi.azureedge.net/files/ebc91af7-c205-463c-9cd5-b54fb86644d2&width=310

**Comment by tofixx** [comment]
use `format=webp` instead.
