### ISSUE TITLE
Check possible usage of Vary headres

### ISSUE THREAD

**Issue by maxklenk** [pichasso/pichasso#89]
Use the Vary header to correctly indicate request headers that need to be included in a cache key. 

https://www.igvita.com/2013/05/01/deploying-webp-via-accept-content-negotiation/
https://blog.stackpath.com/accept-encoding-vary-important
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary
https://www.fastly.com/blog/best-practices-using-vary-header/

**Comment by tofixx** [comment]
done
