### ISSUE TITLE
images not completely generated

### ISSUE THREAD

**Issue by tofixx** [pichasso/pichasso#93]
however some images are not completely rendered and have some part missing. see the gray part in the bottom of https://picasso.openhpi.de/image?file=https://open.hpi.de/files/0d75ded2-3a7f-4f46-bb1d-2851fd91f30a?size=large

**Comment by tofixx** [comment]
![image](https://user-images.githubusercontent.com/4550014/31824498-81cf8206-b5af-11e7-8d4b-a7afe976672d.png)

**Comment by tofixx** [comment]
however removing size=large will resolve that but anyways that is strange... because of the source image is complete

**Comment by franticBIT** [comment]
Why is there the large parameter anyway?

**Comment by tofixx** [comment]
source server closed connection
